project:
  type: website
  output-dir: docs
  resources:
    - google*.html
website:
  title: "Julius's Blog"
  description: "Data Science, Swimming Analytics, and R Programming"
  site-url: https://jbogomolovas2.github.io/Julius-s-Blog/
  open-graph: true
  twitter-card: true
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jbogomolovas2
      - icon: twitter
        href: https://twitter.com/JuliusBogo1
      - icon: linkedin
        href: https://www.linkedin.com/in/julius-bogomolovas-93222a19/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual