<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Julius Bogomolovas">
<meta name="dcterms.date" content="2026-05-24">

<title>Conway–Maxwell–Binomial regression: two-directional dispersion for bounded counts – Julius’s Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../profile.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Conway–Maxwell–Binomial regression: two-directional dispersion for bounded counts – Julius’s Blog">
<meta property="og:description" content="Data Science, Swimming Analytics, and R Programming">
<meta property="og:image" content="https://jbogomolovas2.github.io/Julius-s-Blog/posts/CMB_regression/corals.png">
<meta property="og:site_name" content="Julius's Blog">
<meta property="og:image:height" content="941">
<meta property="og:image:width" content="1672">
<meta name="twitter:title" content="Conway–Maxwell–Binomial regression: two-directional dispersion for bounded counts – Julius’s Blog">
<meta name="twitter:description" content="Data Science, Swimming Analytics, and R Programming">
<meta name="twitter:image" content="https://jbogomolovas2.github.io/Julius-s-Blog/posts/CMB_regression/corals.png">
<meta name="twitter:image-height" content="941">
<meta name="twitter:image-width" content="1672">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Julius’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.r-bloggers.com"> 
<span class="menu-text">R-bloggers</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jbogomolovas2"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/JuliusBogo1"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/julius-bogomolovas-93222a19/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Conway–Maxwell–Binomial regression: two-directional dispersion for bounded counts</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">GLM</div>
                <div class="quarto-category">GLMM</div>
                <div class="quarto-category">Count Regression</div>
                <div class="quarto-category">CMB</div>
                <div class="quarto-category">Biometrics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Julius Bogomolovas </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 24, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-i-got-here" id="toc-how-i-got-here" class="nav-link active" data-scroll-target="#how-i-got-here">How I got here</a></li>
  <li><a href="#the-dispersion-landscape" id="toc-the-dispersion-landscape" class="nav-link" data-scroll-target="#the-dispersion-landscape">The dispersion landscape</a></li>
  <li><a href="#the-implementation" id="toc-the-implementation" class="nav-link" data-scroll-target="#the-implementation">The implementation</a>
  <ul class="collapse">
  <li><a href="#mean-parameterization" id="toc-mean-parameterization" class="nav-link" data-scroll-target="#mean-parameterization">Mean parameterization</a></li>
  <li><a href="#family-registration-on-the-tmb-side" id="toc-family-registration-on-the-tmb-side" class="nav-link" data-scroll-target="#family-registration-on-the-tmb-side">Family registration on the TMB side</a></li>
  </ul></li>
  <li><a href="#a-simulated-three-group-example" id="toc-a-simulated-three-group-example" class="nav-link" data-scroll-target="#a-simulated-three-group-example">A simulated three-group example</a>
  <ul class="collapse">
  <li><a href="#fitting-the-four-candidates" id="toc-fitting-the-four-candidates" class="nav-link" data-scroll-target="#fitting-the-four-candidates">Fitting the four candidates</a></li>
  </ul></li>
  <li><a href="#the-coral-fertilization-study" id="toc-the-coral-fertilization-study" class="nav-link" data-scroll-target="#the-coral-fertilization-study">The coral fertilization study</a>
  <ul class="collapse">
  <li><a href="#the-question" id="toc-the-question" class="nav-link" data-scroll-target="#the-question">The question</a></li>
  <li><a href="#how-they-analyzed-it" id="toc-how-they-analyzed-it" class="nav-link" data-scroll-target="#how-they-analyzed-it">How they analyzed it</a></li>
  <li><a href="#how-we-analyze-it" id="toc-how-we-analyze-it" class="nav-link" data-scroll-target="#how-we-analyze-it">How we analyze it</a></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data">Loading the data</a></li>
  <li><a href="#a-model-free-look-at-dispersion" id="toc-a-model-free-look-at-dispersion" class="nav-link" data-scroll-target="#a-model-free-look-at-dispersion">A model-free look at dispersion</a></li>
  <li><a href="#fitting-six-candidates" id="toc-fitting-six-candidates" class="nav-link" data-scroll-target="#fitting-six-candidates">Fitting six candidates</a></li>
  <li><a href="#what-cmb-found-about-dispersion" id="toc-what-cmb-found-about-dispersion" class="nav-link" data-scroll-target="#what-cmb-found-about-dispersion">What CMB found about dispersion</a></li>
  <li><a href="#confidence-intervals-on-what-we-actually-care-about" id="toc-confidence-intervals-on-what-we-actually-care-about" class="nav-link" data-scroll-target="#confidence-intervals-on-what-we-actually-care-about">Confidence intervals on what we actually care about</a></li>
  <li><a href="#sharpening-the-biological-finding" id="toc-sharpening-the-biological-finding" class="nav-link" data-scroll-target="#sharpening-the-biological-finding">Sharpening the biological finding</a></li>
  </ul></li>
  <li><a href="#when-to-use-what" id="toc-when-to-use-what" class="nav-link" data-scroll-target="#when-to-use-what">When to use what</a></li>
  <li><a href="#bottom-line" id="toc-bottom-line" class="nav-link" data-scroll-target="#bottom-line">Bottom line</a></li>
  <li><a href="#getting-cmb-in-your-r-session" id="toc-getting-cmb-in-your-r-session" class="nav-link" data-scroll-target="#getting-cmb-in-your-r-session">Getting CMB in your R session</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="how-i-got-here" class="level2">
<h2 class="anchored" data-anchor-id="how-i-got-here">How I got here</h2>
<p>For a long time I was fitting cell proliferation counts with Conway-Maxwell-Poisson and a <code>log(n)</code> offset. It worked fine. Counts behaved like rates, the dispersion parameter ν gave me a handle on whether the data were over or underdispersed relative to Poisson, and the offset turned an unbounded count distribution into something that read like a proportion model. Standard applied stats move, nothing exotic.</p>
<p>Then I tried to build a simulator. In the <a href="https://jbogomolovas2.github.io/Julius-s-Blog/posts/comparison/">previous post</a> I wrote a CMP-with-offset data generator so I could check coverage and power before running real experiments. And the simulator started producing counts above the biological ceiling. Cells dividing more times than there are cells. The unbounded count distribution does not know my data has an upper bound, and the offset trick does not enforce one.</p>
<p>In my real data this had not bitten me because proliferation rarely hits the ceiling. So the bound was a silent assumption I had been getting away with for years. The simulator surfaced it.</p>
<p>That sent me reading. The right answer for bounded counts with flexible dispersion is the Conway-Maxwell-Binomial distribution, the bounded analogue of CMP. It spans both dispersion directions through the same ν parameter, and it respects the bound by construction.</p>
<p>The puzzle is why CMB is not a standard tool. Underdispersion in proportion data is a known headache and the workarounds in common use are all unsatisfying. The oldest is the arcsine square-root transformation: apply a variance-stabilizing transform to the observed proportions and fit a Gaussian regression on the transformed values. This throws away the bounded discrete structure of the data, produces coefficients on a scale that does not map cleanly back to rates, and offers no way to model dispersion separately from the mean. The coral fertilization paper we work through later in this post takes exactly this route, and we will see why it leaves a real biological signal on the table. A second workaround is quasi-binomial, which allows the dispersion parameter to fall below 1 but does so without a proper likelihood behind it, so AIC comparisons, likelihood ratio tests, and random effects are all off the table. A third option is to fit a binomial GLM and ignore the underdispersion, accepting standard errors that are wrong in a direction that is hard to predict from the output alone. None of these is what someone would reach for if a clean alternative were sitting in their toolkit.</p>
<p>R support for CMB is thin. The <a href="https://rdrr.io/github/andrewraim/COMMultReg/">COMMultReg package</a> by Andrew Raim <span class="citation" data-cites="COMMultReg">(<a href="#ref-COMMultReg" role="doc-biblioref">Raim, n.d.</a>)</span> provides distribution-level utilities for CMB (density, sampling, normalizing constant, mean, variance) and a full regression interface for the <em>multinomial</em> generalization. The package name is honest about its scope: Conway-Maxwell-<em>Multinomial</em> Regression. The binomial case sits in the distribution module only, in the canonical <code>(m, p, ν)</code> parameterization <span class="citation" data-cites="kadane2016cmb">(<a href="#ref-kadane2016cmb" role="doc-biblioref">Kadane 2016</a>)</span>, with no regression interface, no formula syntax, no dispersion submodel, and no random effects.</p>
<p>So that is what I built. CMB now lives on two public forks: the <a href="https://github.com/jbogomolovas2/adcomp/tree/cmb-family">TMB-side family definition</a> with the auto-differentiable likelihood, and the <a href="https://github.com/jbogomolovas2/glmmTMB/tree/cmb-family">glmmTMB-side integration</a> that wires it into the formula interface so you can write <code>family = compbinomial, dispformula = ~ ...</code> like any other family. It is not on CRAN. Maybe one day. For now if you want to follow along you install from those forks.</p>
<p>This post is two things. First, a short explanation of why CMB is the right tool when your data are bounded and your dispersion is heterogeneous or two-sided. Second, two worked examples: a simulated three-group dataset where you can see the machinery work in controlled conditions, and a real coral fertilization study where CMB sharpens the biological finding the original analysis could not formally test.</p>
</section>
<section id="the-dispersion-landscape" class="level2">
<h2 class="anchored" data-anchor-id="the-dispersion-landscape">The dispersion landscape</h2>
<p>A short conceptual section before code.</p>
<p>You have a bounded count: <span class="math inline">\(y\)</span> successes out of <span class="math inline">\(n\)</span> trials. The default model is binomial, which fixes the variance at <span class="math inline">\(\text{Var}(y) = np(1-p)\)</span> once you condition on the mean. Real data are often more variable than this, sometimes less. The deviation from binomial variance, in either direction, is what people call dispersion.</p>
<p>The standard fix for <em>more</em> variance than binomial is the beta-binomial. It writes the variance as</p>
<p><span class="math display">\[\text{Var}(y) = np(1-p)\,\bigl[1 + (n-1)\rho\bigr], \quad \rho \in [0, 1).\]</span></p>
<p>The dispersion parameter <span class="math inline">\(\rho\)</span> inflates the binomial variance. When <span class="math inline">\(\rho = 0\)</span> you recover binomial. When <span class="math inline">\(\rho \to 1\)</span> the variance approaches the maximum possible for a bounded count. So beta-binomial covers everything from binomial up to the upper bound.</p>
<p>What it does not cover is anything below the binomial line. The constraint <span class="math inline">\(\rho \geq 0\)</span> is not a numerical artifact, it is a property of the family. If your data are <em>less</em> variable than binomial, the BB likelihood pushes <span class="math inline">\(\rho\)</span> against zero and either pegs there (silently behaving as binomial) or fails to converge with a non-positive-definite Hessian. There is no way to wiggle through it.</p>
<p>The Conway-Maxwell-Binomial family does cover both sides. Its variance, approximately, behaves like <span class="math inline">\(np(1-p)/\nu\)</span>, with the dispersion parameter <span class="math inline">\(\nu\)</span> on a multiplicative scale: <span class="math inline">\(\nu = 1\)</span> is binomial, <span class="math inline">\(\nu &lt; 1\)</span> is overdispersed (more variance), <span class="math inline">\(\nu &gt; 1\)</span> is underdispersed (less variance). One parameter, two directions, the bound preserved.</p>
<p>The other natural alternative for rate-like data, CMP with a <code>log(n)</code> offset, fails for a different reason. It is an unbounded count distribution, so the bound is not part of the model. In situations where counts rarely approach <span class="math inline">\(n\)</span> the offset trick can be a decent approximation, but it is not a principled choice for bounded data and it breaks at the ceiling.</p>
<p>A picture of what these three families look like for the same mean and different ν values:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>n  <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>k  <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span>n</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># COMMultReg uses canonical (m, p, nu) parameterization. At p = 0.5 the</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># CMB pmf is symmetric about n/2 for any nu, so the mean equals n/2 = 10</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># in all three regimes without inverting the mean-p relation.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>p_over  <span class="ot">&lt;-</span> <span class="fu">sapply</span>(k, <span class="cf">function</span>(x) <span class="fu">d_cmb</span>(x, <span class="at">m =</span> n, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">nu =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>p_bin   <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(k, n, <span class="fl">0.5</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>p_under <span class="ot">&lt;-</span> <span class="fu">sapply</span>(k, <span class="cf">function</span>(x) <span class="fu">d_cmb</span>(x, <span class="at">m =</span> n, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">nu =</span> <span class="fl">2.0</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>df_pmf <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">k =</span> k, <span class="at">pmf =</span> p_over,  <span class="at">regime =</span> <span class="st">"overdispersed (ν &lt; 1)"</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">k =</span> k, <span class="at">pmf =</span> p_bin,   <span class="at">regime =</span> <span class="st">"binomial (ν = 1)"</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">k =</span> k, <span class="at">pmf =</span> p_under, <span class="at">regime =</span> <span class="st">"underdispersed (ν &gt; 1)"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">regime =</span> <span class="fu">factor</span>(regime, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"overdispersed (ν &lt; 1)"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"binomial (ν = 1)"</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"underdispersed (ν &gt; 1)"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  )))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_pmf, <span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> pmf, <span class="at">color =</span> regime)) <span class="sc">+</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> regime), <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#d7191c"</span>, <span class="st">"grey30"</span>, <span class="st">"#2c7bb6"</span>)) <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"y (successes out of n = 20)"</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"probability mass"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Same mean rate, three dispersion regimes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/dispersion-densities-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>CMB pmf for n = 20 at mean rate 0.5, under three dispersion regimes. The binomial baseline (ν = 1) is shown in grey. Overdispersion (ν = 0.5) flattens the mass relative to binomial. Underdispersion (ν = 2) concentrates it around the mean. Densities computed with <code>COMMultReg::d_cmb</code>.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-implementation" class="level2">
<h2 class="anchored" data-anchor-id="the-implementation">The implementation</h2>
<p>Two things needed to happen to get CMB working as a regression family in R.</p>
<section id="mean-parameterization" class="level3">
<h3 class="anchored" data-anchor-id="mean-parameterization">Mean parameterization</h3>
<p>The standard CMB pmf <span class="citation" data-cites="kadane2016cmb">(<a href="#ref-kadane2016cmb" role="doc-biblioref">Kadane 2016</a>)</span> is</p>
<p><span class="math display">\[P(X = k \mid n, p, \nu) = \frac{1}{Z(n, p, \nu)}\binom{n}{k}^\nu p^k (1-p)^{n-k}\]</span></p>
<p>with normalizing constant <span class="math inline">\(Z(n, p, \nu) = \sum_{j=0}^{n} \binom{n}{j}^\nu p^j (1-p)^{n-j}\)</span>. This is a finite sum, which matters: unlike the CMP normalizing constant, the CMB version does not need truncation or special-function approximations.</p>
<p>The catch is the role of <span class="math inline">\(p\)</span>. When <span class="math inline">\(\nu = 1\)</span> the family reduces to binomial and <span class="math inline">\(p\)</span> equals the mean rate. When <span class="math inline">\(\nu \neq 1\)</span>, <span class="math inline">\(p\)</span> is just a canonical parameter and the mean <span class="math inline">\(\mu = E[X]/n\)</span> depends on both <span class="math inline">\(p\)</span> and <span class="math inline">\(\nu\)</span> together. There is no closed-form expression. This makes the canonical parameterization unusable for regression. If you wrote <code>logit(p) ~ X</code>, your coefficients would be shifts on a parameter that mixes mean and dispersion in a way the reader cannot interpret.</p>
<p>What the implementation does, following the pattern glmmTMB uses for negative binomial and beta-binomial and the mean parameterization Huang <span class="citation" data-cites="huang2017meanCMP">(<a href="#ref-huang2017meanCMP" role="doc-biblioref">Huang 2017</a>)</span> introduced for CMP, is the <em>mean-parametrized</em> version. Given a target mean <span class="math inline">\(\mu\)</span> and a dispersion <span class="math inline">\(\nu\)</span>, solve numerically for the <span class="math inline">\(p\)</span> that satisfies <span class="math inline">\(E[X \mid n, p, \nu] = n\mu\)</span>, then use that <span class="math inline">\(p\)</span> inside the likelihood. The user-facing model is then:</p>
<pre><code>logit(μ) = Xβ        # mean rate, modeled like any binomial-family GLM
log(ν)   = Zγ        # dispersion, modeled separately</code></pre>
<p>The Newton iteration to solve for <span class="math inline">\(p\)</span> runs at every likelihood evaluation. This is fine because TMB handles the derivatives by automatic differentiation, so the gradient of the marginal likelihood propagates through the inner solve without any hand-coded chain rule. This is the main reason I built on TMB rather than coding the family in plain R.</p>
</section>
<section id="family-registration-on-the-tmb-side" class="level3">
<h3 class="anchored" data-anchor-id="family-registration-on-the-tmb-side">Family registration on the TMB side</h3>
<p>The <code>compbinomial</code> family is added to TMB’s family list with its own log-density function, then exposed to glmmTMB through its dispatch. Once registered it inherits everything: random effects, dispformula, zero-inflation if you want it, the standard <code>fixef()</code> / <code>ranef()</code> / <code>vcov()</code> accessors. The model code looks identical to any other glmmTMB fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install from forks (one-time)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"jbogomolovas2/adcomp"</span>,  <span class="at">ref =</span> <span class="st">"cmb-family"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">subdir =</span> <span class="st">"TMB"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"jbogomolovas2/glmmTMB"</span>, <span class="at">ref =</span> <span class="st">"cmb-family"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">subdir =</span> <span class="st">"glmmTMB"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use it like any glmmTMB family</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> group <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">dispformula =</span> <span class="sc">~</span> group,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">family      =</span> compbinomial,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">data        =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That’s the whole interface. From the user’s side it is just another family. The work was making it behave that way.</p>
</section>
</section>
<section id="a-simulated-three-group-example" class="level2">
<h2 class="anchored" data-anchor-id="a-simulated-three-group-example">A simulated three-group example</h2>
<p>The cleanest way to see the families fail and succeed is to put them on data where we control the truth. We simulate three groups of observations from CMB itself, with the same trial size and the same mean rate in each group, but with three different dispersion parameters: ν = 0.5 (overdispersed), ν = 1 (binomial), ν = 2 (underdispersed). Each group has sixty observations of <code>y</code> out of <code>n = 30</code> trials. We set the canonical parameter <code>p = 0.5</code> so the CMB distribution is symmetric about <code>n/2</code> for any ν, which puts the true mean at exactly <code>15</code> in all three groups without needing to invert the mean-p relation. We then fit four models on the pooled data and compare them: binomial (no dispersion submodel), beta-binomial with <code>dispformula = ~ group</code>, CMP-with-offset with <code>dispformula = ~ group</code>, and CMB with <code>dispformula = ~ group</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(COMMultReg)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>n_trials  <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>n_per_grp <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>p_true    <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>nu_true   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">over =</span> <span class="fl">0.5</span>, <span class="at">binomial =</span> <span class="fl">1.0</span>, <span class="at">under =</span> <span class="fl">2.0</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">names</span>(nu_true), <span class="cf">function</span>(g) {</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> g,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">n     =</span> n_trials,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y     =</span> <span class="fu">r_cmb</span>(n_per_grp, <span class="at">m =</span> n_trials, <span class="at">p =</span> p_true, <span class="at">nu =</span> nu_true[[g]])</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>})) <span class="sc">|&gt;</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="fu">factor</span>(group, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"over"</span>, <span class="st">"binomial"</span>, <span class="st">"under"</span>)),</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">miss  =</span> n <span class="sc">-</span> y</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(group) <span class="sc">|&gt;</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_obs            =</span> dplyr<span class="sc">::</span><span class="fu">n</span>(),</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_rate        =</span> <span class="fu">mean</span>(y <span class="sc">/</span> n),</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">obs_var          =</span> <span class="fu">var</span>(y),</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">binomial_var     =</span> n_trials <span class="sc">*</span> <span class="fu">mean</span>(y<span class="sc">/</span>n) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">mean</span>(y<span class="sc">/</span>n)),</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">var_ratio        =</span> obs_var <span class="sc">/</span> binomial_var,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups          =</span> <span class="st">"drop"</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">n_obs</th>
<th style="text-align: right;">mean_rate</th>
<th style="text-align: right;">obs_var</th>
<th style="text-align: right;">binomial_var</th>
<th style="text-align: right;">var_ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">over</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.528</td>
<td style="text-align: right;">17.68898</td>
<td style="text-align: right;">7.476</td>
<td style="text-align: right;">2.3661290</td>
</tr>
<tr class="even">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.487</td>
<td style="text-align: right;">10.44379</td>
<td style="text-align: right;">7.495</td>
<td style="text-align: right;">1.3934147</td>
</tr>
<tr class="odd">
<td style="text-align: left;">under</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.504</td>
<td style="text-align: right;">2.79548</td>
<td style="text-align: right;">7.499</td>
<td style="text-align: right;">0.3727601</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The last column is the empirical analogue of 1/ν. We expect about 2.0 for the overdispersed group, 1.0 for binomial, and 0.5 for the underdispersed group. The observed ratios (2.37, 1.39, 0.37) match the expected pattern, with the binomial group running a little high by chance at this sample size.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_data, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> y <span class="sc">/</span> n, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">height =</span> <span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"grey20"</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">over =</span> <span class="st">"#d7191c"</span>, <span class="at">binomial =</span> <span class="st">"grey30"</span>, <span class="at">under =</span> <span class="st">"#2c7bb6"</span>)) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"observed rate"</span>, <span class="at">title =</span> <span class="st">"Simulated rates by group"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/sim-quick-look-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Simulated y / n by group. The overdispersed group has visibly more spread than the binomial baseline; the underdispersed group has visibly less.</figcaption>
</figure>
</div>
</div>
</div>
<section id="fitting-the-four-candidates" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-four-candidates">Fitting the four candidates</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>safe_fit <span class="ot">&lt;-</span> <span class="cf">function</span>(expr) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">fit =</span> <span class="fu">eval.parent</span>(<span class="fu">substitute</span>(expr)), <span class="at">error =</span> <span class="cn">NA_character_</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) <span class="fu">list</span>(<span class="at">fit =</span> <span class="cn">NULL</span>, <span class="at">error =</span> <span class="fu">conditionMessage</span>(e))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>form_bound <span class="ot">&lt;-</span> <span class="fu">cbind</span>(y, miss) <span class="sc">~</span> group</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>form_cmp   <span class="ot">&lt;-</span> y <span class="sc">~</span> group <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(n))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>fits <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">binomial =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> binomial, <span class="at">data =</span> sim_data)),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">bb       =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> betabinomial,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                              <span class="at">dispformula =</span> <span class="sc">~</span> group, <span class="at">data =</span> sim_data)),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">cmp      =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_cmp,   <span class="at">family =</span> compois,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                              <span class="at">dispformula =</span> <span class="sc">~</span> group, <span class="at">data =</span> sim_data)),</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">cmb      =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> compbinomial,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>                              <span class="at">dispformula =</span> <span class="sc">~</span> group, <span class="at">data =</span> sim_data))</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in finalizeTMB(TMBStruc, obj, fit, h, data.tmb.old): Model convergence
problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>compare_tbl <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">names</span>(fits), <span class="cf">function</span>(nm) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> fits[[nm]]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(x<span class="sc">$</span>fit)) {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">data.frame</span>(<span class="at">family =</span> nm, <span class="at">df =</span> <span class="cn">NA_real_</span>, <span class="at">AIC =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">converged =</span> <span class="cn">FALSE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">family    =</span> nm,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">df        =</span> <span class="fu">attr</span>(<span class="fu">logLik</span>(x<span class="sc">$</span>fit), <span class="st">"df"</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIC       =</span> <span class="fu">AIC</span>(x<span class="sc">$</span>fit),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">converged =</span> <span class="fu">isTRUE</span>(x<span class="sc">$</span>fit<span class="sc">$</span>sdr<span class="sc">$</span>pdHess),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>})) <span class="sc">|&gt;</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">dAIC =</span> AIC <span class="sc">-</span> <span class="fu">min</span>(AIC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="fu">is.na</span>(AIC), AIC)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(compare_tbl, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">family</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: left;">converged</th>
<th style="text-align: right;">dAIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cmb</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">894.63</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">cmp</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">901.93</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">945.45</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">50.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">bb</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>CMB wins. CMP-offset comes in a respectable second, a little behind. Plain binomial sits at +51 AIC, which is the expected penalty for a model with no dispersion structure at all. And beta-binomial does not finish: the row shows <code>converged = FALSE</code> and <code>AIC = NA</code>. The optimizer did not trip on a numerical artifact, it ran into the rho ≥ 0 wall and could not find any set of parameter values that simultaneously fit all three groups. BB is the delicate flower here, it wilts from the slightest whiff of underdispersion dragging the whole fit along.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cmb_nu_by_group <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, groups) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  grid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">group =</span> <span class="fu">factor</span>(groups, <span class="at">levels =</span> groups))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  X    <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> group, <span class="at">data =</span> grid)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  V    <span class="ot">&lt;-</span> <span class="fu">vcov</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  eta  <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(X <span class="sc">%*%</span> beta)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  se   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(X <span class="sc">%*%</span> V <span class="sc">%*%</span> <span class="fu">t</span>(X)))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  grid <span class="sc">|&gt;</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">nu_hat =</span> <span class="fu">exp</span>(eta),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower  =</span> <span class="fu">exp</span>(eta <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">upper  =</span> <span class="fu">exp</span>(eta <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>bb_rho_by_group <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, groups) {</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  grid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">group =</span> <span class="fu">factor</span>(groups, <span class="at">levels =</span> groups))</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  X    <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> group, <span class="at">data =</span> grid)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  V    <span class="ot">&lt;-</span> <span class="fu">vcov</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  eta  <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(X <span class="sc">%*%</span> beta)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  phi  <span class="ot">&lt;-</span> <span class="fu">exp</span>(eta)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  grid <span class="sc">|&gt;</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">phi          =</span> phi,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">rho_overdisp =</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> phi),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">at_boundary  =</span> phi <span class="sc">&gt;</span> <span class="dv">50</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>nu_tbl  <span class="ot">&lt;-</span> <span class="fu">cmb_nu_by_group</span>(fits<span class="sc">$</span>cmb<span class="sc">$</span>fit, <span class="fu">c</span>(<span class="st">"over"</span>, <span class="st">"binomial"</span>, <span class="st">"under"</span>))</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>nu_tbl<span class="sc">$</span>nu_true <span class="ot">&lt;-</span> nu_true[<span class="fu">c</span>(<span class="st">"over"</span>, <span class="st">"binomial"</span>, <span class="st">"under"</span>)]</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>rho_tbl <span class="ot">&lt;-</span> <span class="fu">bb_rho_by_group</span>(fits<span class="sc">$</span>bb<span class="sc">$</span>fit, <span class="fu">c</span>(<span class="st">"over"</span>, <span class="st">"binomial"</span>, <span class="st">"under"</span>))</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(nu_tbl, <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"CMB ν estimates against simulated truth"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>CMB ν estimates against simulated truth</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">nu_hat</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: right;">nu_true</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">over</td>
<td style="text-align: right;">0.410</td>
<td style="text-align: right;">0.281</td>
<td style="text-align: right;">0.598</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">0.714</td>
<td style="text-align: right;">0.494</td>
<td style="text-align: right;">1.030</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">under</td>
<td style="text-align: right;">2.791</td>
<td style="text-align: right;">1.947</td>
<td style="text-align: right;">4.000</td>
<td style="text-align: right;">2.0</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(rho_tbl, <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Beta-binomial ρ by group, with boundary flag"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Beta-binomial ρ by group, with boundary flag</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">phi</th>
<th style="text-align: right;">rho_overdisp</th>
<th style="text-align: left;">at_boundary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">over</td>
<td style="text-align: right;">20.982</td>
<td style="text-align: right;">0.045</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">76.442</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">under</td>
<td style="text-align: right;">62271613.949</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: left;">TRUE</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>CMB recovery is decent: every 95% interval covers its simulated truth, and the point estimates land in the right neighborhood. At sixty observations per group with moderate effect sizes, that is about what we should expect.</p>
<p>The beta-binomial table tells two stories at once. On the overdispersed group, BB does its job: rho is 0.045 and the boundary flag is <code>FALSE</code>. On the binomial group, BB pushes rho down to 0.013 and trips <code>at_boundary = TRUE</code>, which is correct behavior. There is no overdispersion to estimate, so the family collapses toward the binomial limit, and that is what we want. The underdispersed group is where things break. Phi explodes to about 6 x 10^7 and rho goes to zero, not because BB has discovered “very little overdispersion” but because the optimizer is running off to infinity in search of a parameter value that does not exist in the family. Combined with the <code>converged = FALSE</code> we saw in the AIC table, this is what hitting the rho &gt;= 0 wall looks like in practice. The two boundary hits look identical in the table and mean opposite things: one is the family doing the right thing, the other is the family unable to do anything at all.</p>
<p>A picture of the recovery:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nu_tbl, <span class="fu">aes</span>(<span class="at">x =</span> nu_hat, <span class="at">y =</span> group)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey45"</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower, <span class="at">xmax =</span> upper), <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> nu_true), <span class="at">color =</span> <span class="st">"#d7191c"</span>, <span class="at">shape =</span> <span class="dv">4</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">4</span>, <span class="at">stroke =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"CMB ν estimate (log scale, with 95% CI)"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Simulated truth (red crosses) vs CMB estimate (black)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/sim-nu-plot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>CMB ν estimates with 95% confidence intervals, against the simulated values (red crosses). The dashed vertical line is the binomial baseline. CMB hits all three regimes.</figcaption>
</figure>
</div>
</div>
</div>
<p>And finally, the practical payoff: what does the confidence interval on the group mean look like under each model?</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ci_widths <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">c</span>(<span class="st">"binomial"</span>, <span class="st">"bb"</span>, <span class="st">"cmb"</span>), <span class="cf">function</span>(m) {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  f <span class="ot">&lt;-</span> fits[[m]]<span class="sc">$</span>fit</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(f)) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(emmeans<span class="sc">::</span><span class="fu">emmeans</span>(f, <span class="sc">~</span> group, <span class="at">type =</span> <span class="st">"response"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">model =</span> m, <span class="at">ci_width =</span> asymp.UCL <span class="sc">-</span> asymp.LCL)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>ci_widths <span class="sc">|&gt;</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(group, model, ci_width) <span class="sc">|&gt;</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> model, <span class="at">values_from =</span> ci_width,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">names_prefix =</span> <span class="st">"ci_"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">caption =</span> <span class="st">"95% CI widths on the per-group mean rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>95% CI widths on the per-group mean rate</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">ci_binomial</th>
<th style="text-align: right;">ci_bb</th>
<th style="text-align: right;">ci_cmb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">over</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: right;">0.0701</td>
<td style="text-align: right;">0.0701</td>
</tr>
<tr class="even">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: right;">0.0541</td>
<td style="text-align: right;">0.0542</td>
</tr>
<tr class="odd">
<td style="text-align: left;">under</td>
<td style="text-align: right;">0.0462</td>
<td style="text-align: right;">0.0462</td>
<td style="text-align: right;">0.0279</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Same data, three stories. If the group is overdispersed, BB and CMB both recognize it and widen the CI. If the group is underdispersed, only CMB recognizes it; BB cannot, because its dispersion floor is rho = 0. That is the asymmetry. Beta-binomial sees half the dispersion landscape. CMB sees both halves.</p>
</section>
</section>
<section id="the-coral-fertilization-study" class="level2">
<h2 class="anchored" data-anchor-id="the-coral-fertilization-study">The coral fertilization study</h2>
<p>The simulated example showed CMB doing its job on data we built. The next test is real data, where there is no simulated truth, no guarantee any family fits well, and the biology might or might not be visible once the statistical work is done.</p>
<p>The dataset comes from Puisay et al. <span class="citation" data-cites="puisay2024coral">(<a href="#ref-puisay2024coral" role="doc-biblioref">Puisay et al. 2024</a>)</span>, <a href="https://www.sciencedirect.com/science/article/abs/pii/S0022098123000527">How thermal priming of coral gametes shapes fertilization success</a>, with the raw spreadsheet publicly archived on <a href="https://zenodo.org/records/8032395">Zenodo</a> <span class="citation" data-cites="puisay2024coral_data">(<a href="#ref-puisay2024coral_data" role="doc-biblioref">Puisay et al. 2023</a>)</span>. The original study asked whether pre-exposing the gametes of a broadcast-spawning coral (<em>Acropora cytherea</em>) to elevated temperature, before fertilization, can rescue fertilization success when fertilization itself occurs at warmer ocean temperatures.</p>
<section id="the-question" class="level3">
<h3 class="anchored" data-anchor-id="the-question">The question</h3>
<p>The experiment is a clean 2 × 2 × 2 × 4 factorial. Each replicate vial holds a known number of eggs (range 33 to 457, mean about 160) and a controlled batch of sperm, under these conditions:</p>
<ul>
<li>Sperm pre-exposed at 27°C or 30°C</li>
<li>Oocytes pre-exposed at 27°C or 30°C</li>
<li>Pre-exposure lasting 0.5, 1, 1.5, or 2 hours</li>
<li>Fertilization itself carried out at either 27°C (control) or 30°C (warm, the climate-change scenario)</li>
</ul>
<p>The outcome is the count of embryos that developed normally (2-cell, 4-cell, or more-cell stage) out of the total eggs scored. Six replicates per cell, 192 vials in total, and just over 30,000 eggs scored. This is a textbook bounded count: <code>y</code> successes out of <code>n</code> trials, with <code>n</code> known per vial.</p>
</section>
<section id="how-they-analyzed-it" class="level3">
<h3 class="anchored" data-anchor-id="how-they-analyzed-it">How they analyzed it</h3>
<p>The authors fit a binomial-style GLM, but with a twist that matters here. They applied an arcsine square-root transformation to the proportions, then ran <code>glm()</code> on the transformed values. This is one of the three workarounds for proportion data that section 2 listed: throw away the bounded discrete structure, get coefficients on a scale that does not map cleanly back to rates, and accept that you cannot model dispersion separately from the mean. It is what people reach for when proportion data misbehave and there is no proper bounded-count family with dispersion structure in the toolkit they are using.</p>
<p>The authors noticed that dispersion in their data was doing something interesting. From their discussion section:</p>
<blockquote class="blockquote">
<p>“Interestingly, all things being equal, the fertilization success was more variable at 30°C, which may indicate opportunity for selection during the fertilization success. Furthermore, when considering the particular treatment where the thermal priming of gametes increased the fertilization success at 30°C, we observed a reduction of the variation of the fertilization success […] This experimental reduction in the variation of the fertilization success may imply that selection occurred on a pool of diverse gametes.”</p>
</blockquote>
<p>This is exactly the kind of observation a CMB model is built to formalize. Warm fertilization produces more variable outcomes than control. Successful priming both raises the mean and reduces the variability. Their analysis let them comment on this qualitatively in the discussion but did not let them attach a number to it, give it a confidence interval, or test it formally against the mean structure. They could see the dispersion pattern but could not model it.</p>
</section>
<section id="how-we-analyze-it" class="level3">
<h3 class="anchored" data-anchor-id="how-we-analyze-it">How we analyze it</h3>
<p>Same mean structure as theirs (a three-way interaction of fertilization temperature, pre-exposure time, and the cross of sperm × oocyte priming), but with three changes. First, we go back to the proper binomial scale via <code>cbind(y, n - y)</code>, no transformation. Second, we use <code>family = compbinomial</code> and let <code>dispformula = ~ fert_temp * treatment</code> model the dispersion across the eight (fert_temp × treatment) cells. Third, we add <code>(1 | site)</code> to capture shared variation across the two fertilization-temperature samples drawn from the same pre-exposure batch. We then compare the same set of candidate families introduced in the simulated example.</p>
</section>
<section id="loading-the-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-data">Loading the data</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"/Users/jb/Downloads/DATA (1).xlsx"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sheet =</span> <span class="st">"GLM models data 2014"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">skip  =</span> <span class="dv">1</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>mod_data <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">transmute</span>(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">site      =</span> <span class="fu">factor</span>(Site),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fert_temp =</span> <span class="fu">factor</span>(Temp,    <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>)),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_s    =</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">Temp S</span><span class="st">`</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>)),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_o    =</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">Temp O</span><span class="st">`</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>)),</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">time      =</span> <span class="fu">as.numeric</span>(time),</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">n         =</span> <span class="fu">as.integer</span>(total),</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y         =</span> <span class="fu">as.integer</span>(<span class="st">`</span><span class="at">2 Cells</span><span class="st">`</span>) <span class="sc">+</span> <span class="fu">as.integer</span>(<span class="st">`</span><span class="at">4 Cells</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>                <span class="fu">as.integer</span>(<span class="st">`</span><span class="at">More Cells</span><span class="st">`</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">miss      =</span> n <span class="sc">-</span> y,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">treatment =</span> <span class="fu">factor</span>(<span class="fu">paste0</span>(<span class="st">"O"</span>, temp_o, <span class="st">"S"</span>, temp_s),</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"O27S27"</span>, <span class="st">"O27S30"</span>, <span class="st">"O30S27"</span>, <span class="st">"O30S30"</span>))</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">rows =</span> <span class="fu">nrow</span>(mod_data),</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_eggs =</span> <span class="fu">sum</span>(mod_data<span class="sc">$</span>n),</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_fertilized =</span> <span class="fu">sum</span>(mod_data<span class="sc">$</span>y),</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">overall_rate =</span> <span class="fu">round</span>(<span class="fu">sum</span>(mod_data<span class="sc">$</span>y) <span class="sc">/</span> <span class="fu">sum</span>(mod_data<span class="sc">$</span>n), <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            rows       total_eggs total_fertilized     overall_rate 
         192.000        30465.000        25458.000            0.836 </code></pre>
</div>
</div>
</section>
<section id="a-model-free-look-at-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="a-model-free-look-at-dispersion">A model-free look at dispersion</h3>
<p>Before fitting anything, we check whether the data really do have heterogeneous dispersion across treatments. For each of the 32 treatment cells (2 fertilization temps × 4 priming treatments × 4 pre-exposure times, 6 replicates each), we compute a model-free binomial-index-of-dispersion: the Pearson chi-square against a binomial null with the cell’s own mean rate, divided by degrees of freedom. Values above 1 indicate overdispersion, below 1 indicate underdispersion.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bid_screen <span class="ot">&lt;-</span> mod_data <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(fert_temp, treatment, time) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_bar =</span> <span class="fu">sum</span>(y) <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">BID   =</span> <span class="fu">sum</span>((y <span class="sc">-</span> n <span class="sc">*</span> p_bar)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">pmax</span>(n <span class="sc">*</span> p_bar <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_bar), <span class="fl">1e-8</span>)) <span class="sc">/</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>              (dplyr<span class="sc">::</span><span class="fu">n</span>() <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>bid_screen <span class="sc">|&gt;</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(fert_temp) <span class="sc">|&gt;</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">cells       =</span> dplyr<span class="sc">::</span><span class="fu">n</span>(),</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_BID     =</span> <span class="fu">round</span>(<span class="fu">min</span>(BID), <span class="dv">2</span>),</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_BID  =</span> <span class="fu">round</span>(<span class="fu">median</span>(BID), <span class="dv">2</span>),</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_BID     =</span> <span class="fu">round</span>(<span class="fu">max</span>(BID), <span class="dv">2</span>),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_under_1 =</span> <span class="fu">round</span>(<span class="fu">mean</span>(BID <span class="sc">&lt;</span> <span class="dv">1</span>), <span class="dv">2</span>),</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">fert_temp</th>
<th style="text-align: right;">cells</th>
<th style="text-align: right;">min_BID</th>
<th style="text-align: right;">median_BID</th>
<th style="text-align: right;">max_BID</th>
<th style="text-align: right;">pct_under_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">7.05</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">15.16</td>
<td style="text-align: right;">0.12</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At control fertilization (27°C), the median BID is below 1 and 70% of cells sit on the underdispersed side, some quite strongly (minimum BID around 0.18). At warm fertilization (30°C), the median jumps to about 4.6, with the most extreme cells running up around 15. The data have heterogeneous, two-directional dispersion structure, exactly the regime CMB is designed for and exactly the regime BB cannot represent.</p>
<p>A picture of all 32 cells:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bid_screen,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(time), <span class="at">y =</span> BID, <span class="at">color =</span> fert_temp)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey45"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> treatment, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"27"</span> <span class="ot">=</span> <span class="st">"#2c7bb6"</span>, <span class="st">"30"</span> <span class="ot">=</span> <span class="st">"#d7191c"</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">name =</span> <span class="st">"Fertilization °C"</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Pre-exposure time (h)"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"BID (log scale)"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Model-free dispersion screen by treatment"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/coral-bid-plot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Model-free dispersion screen by treatment. Cells above the dashed line are overdispersed, below are underdispersed. Warm fertilization (red) sits almost entirely above; control (blue) sits mostly below.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-six-candidates" class="level3">
<h3 class="anchored" data-anchor-id="fitting-six-candidates">Fitting six candidates</h3>
<p>Six families this time. The four from the simulated section, plus the two constant-dispersion variants (beta-binomial and CMB with <code>dispformula = ~ 1</code>) to confirm that the by-treatment dispersion submodel earns its degrees of freedom on real data. Random intercept on site captures shared variation across the two fertilization-temperature samples drawn from each pre-exposure batch.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>safe_fit <span class="ot">&lt;-</span> <span class="cf">function</span>(expr) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">fit =</span> <span class="fu">eval.parent</span>(<span class="fu">substitute</span>(expr)), <span class="at">error =</span> <span class="cn">NA_character_</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) <span class="fu">list</span>(<span class="at">fit =</span> <span class="cn">NULL</span>, <span class="at">error =</span> <span class="fu">conditionMessage</span>(e))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>form_bound <span class="ot">&lt;-</span> <span class="fu">cbind</span>(y, miss) <span class="sc">~</span> fert_temp <span class="sc">*</span> time <span class="sc">*</span> treatment <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> site)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>form_cmp   <span class="ot">&lt;-</span> y <span class="sc">~</span> fert_temp <span class="sc">*</span> time <span class="sc">*</span> treatment <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(n)) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> site)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>fits <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">binomial      =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> binomial, <span class="at">data =</span> mod_data)),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">bb_constant   =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> betabinomial,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mod_data)),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">bb_by_treat   =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> betabinomial,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dispformula =</span> <span class="sc">~</span> fert_temp <span class="sc">*</span> treatment, <span class="at">data =</span> mod_data)),</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">cmp_offset    =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_cmp,   <span class="at">family =</span> compois,</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dispformula =</span> <span class="sc">~</span> fert_temp <span class="sc">*</span> treatment, <span class="at">data =</span> mod_data)),</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">cmb_constant  =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> compbinomial,</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mod_data)),</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">cmb_by_treat  =</span> <span class="fu">safe_fit</span>(<span class="fu">glmmTMB</span>(form_bound, <span class="at">family =</span> compbinomial,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dispformula =</span> <span class="sc">~</span> fert_temp <span class="sc">*</span> treatment, <span class="at">data =</span> mod_data))</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in finalizeTMB(TMBStruc, obj, fit, h, data.tmb.old): Model convergence
problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in finalizeTMB(TMBStruc, obj, fit, h, data.tmb.old): Model convergence
problem; false convergence (8). See vignette('troubleshooting'),
help('diagnose')</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>compare_tbl <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">names</span>(fits), <span class="cf">function</span>(nm) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> fits[[nm]]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(x<span class="sc">$</span>fit)) {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">data.frame</span>(<span class="at">family =</span> nm, <span class="at">df =</span> <span class="cn">NA_real_</span>, <span class="at">AIC =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">converged =</span> <span class="cn">FALSE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">family    =</span> nm,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">df        =</span> <span class="fu">attr</span>(<span class="fu">logLik</span>(x<span class="sc">$</span>fit), <span class="st">"df"</span>),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIC       =</span> <span class="fu">AIC</span>(x<span class="sc">$</span>fit),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">converged =</span> <span class="fu">isTRUE</span>(x<span class="sc">$</span>fit<span class="sc">$</span>sdr<span class="sc">$</span>pdHess),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>})) <span class="sc">|&gt;</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">dAIC =</span> AIC <span class="sc">-</span> <span class="fu">min</span>(AIC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="fu">is.na</span>(AIC), AIC)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(compare_tbl, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">family</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: left;">converged</th>
<th style="text-align: right;">dAIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cmb_by_treat</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1308.82</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">cmp_offset</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1327.89</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">19.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cmb_constant</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">1356.92</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">48.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">bb_constant</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">1357.98</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">49.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">binomial</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">1594.79</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">285.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">bb_by_treat</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Binomial sits at +286 AIC, which is the price of ignoring the dispersion structure entirely. Among the families that try to model dispersion, CMB-by-treatment wins by 19 AIC over CMP-offset and by 48 over the constant-dispersion variants. CMP-offset finishes second, which is honest: at the rates and trial sizes here (rates 0.46 to 0.97, trial sizes 33 to 457), the upper bound is not strongly binding for most cells, so the unbounded-count approximation is not catastrophic. It still loses to CMB by a clear margin. Beta-binomial with by-treatment dispersion did not converge, as the simulated example predicted.</p>
</section>
<section id="what-cmb-found-about-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="what-cmb-found-about-dispersion">What CMB found about dispersion</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>disp_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fert_temp =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>)),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"O27S27"</span>, <span class="st">"O27S30"</span>, <span class="st">"O30S27"</span>, <span class="st">"O30S30"</span>),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"O27S27"</span>, <span class="st">"O27S30"</span>, <span class="st">"O30S27"</span>, <span class="st">"O30S30"</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>cmb_nu_by_cell <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, grid) {</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  X    <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> fert_temp <span class="sc">*</span> treatment, <span class="at">data =</span> grid)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  V    <span class="ot">&lt;-</span> <span class="fu">vcov</span>(fit)<span class="sc">$</span>disp</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  eta  <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(X <span class="sc">%*%</span> beta)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  se   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(X <span class="sc">%*%</span> V <span class="sc">%*%</span> <span class="fu">t</span>(X)))</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  grid <span class="sc">|&gt;</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">nu_hat =</span> <span class="fu">exp</span>(eta),</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower  =</span> <span class="fu">exp</span>(eta <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se),</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">upper  =</span> <span class="fu">exp</span>(eta <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cmb_nu_by_cell</span>(fits<span class="sc">$</span>cmb_by_treat<span class="sc">$</span>fit, disp_grid),</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"CMB ν by treatment cell"</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>CMB ν by treatment cell</caption>
<thead>
<tr class="header">
<th style="text-align: left;">fert_temp</th>
<th style="text-align: left;">treatment</th>
<th style="text-align: right;">nu_hat</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O27S27</td>
<td style="text-align: right;">0.921</td>
<td style="text-align: right;">0.508</td>
<td style="text-align: right;">1.671</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O27S27</td>
<td style="text-align: right;">0.143</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">0.271</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O27S30</td>
<td style="text-align: right;">0.947</td>
<td style="text-align: right;">0.527</td>
<td style="text-align: right;">1.700</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O27S30</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.241</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O30S27</td>
<td style="text-align: right;">0.359</td>
<td style="text-align: right;">0.190</td>
<td style="text-align: right;">0.676</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O30S27</td>
<td style="text-align: right;">0.136</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">0.249</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O30S30</td>
<td style="text-align: right;">1.663</td>
<td style="text-align: right;">0.936</td>
<td style="text-align: right;">2.955</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O30S30</td>
<td style="text-align: right;">0.303</td>
<td style="text-align: right;">0.168</td>
<td style="text-align: right;">0.548</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>CMB sees a clean two-temperature story. Every warm-fertilization cell is strongly overdispersed, with ν between 0.13 and 0.30 and CIs nowhere near 1. The control cells are quieter: two are statistically binomial, one (O30S27) is clearly overdispersed, and one (O30S30, the double-primed condition) has a point estimate of ν ≈ 1.66 with a CI that just brushes 1. That last cell is exactly the underdispersion the paper noticed in the discussion. CMB does not formally call it significant at the 95% level, but it sees the direction the authors described, and it puts numbers on it.</p>
<p>A picture of the CMB ν surface:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>cmb_nu_tbl <span class="ot">&lt;-</span> <span class="fu">cmb_nu_by_cell</span>(fits<span class="sc">$</span>cmb_by_treat<span class="sc">$</span>fit, disp_grid)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cmb_nu_tbl,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> nu_hat, <span class="at">y =</span> <span class="fu">interaction</span>(treatment, fert_temp, <span class="at">sep =</span> <span class="st">" | "</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> fert_temp)) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey45"</span>) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower, <span class="at">xmax =</span> upper), <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"27"</span> <span class="ot">=</span> <span class="st">"#2c7bb6"</span>, <span class="st">"30"</span> <span class="ot">=</span> <span class="st">"#d7191c"</span>),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">name =</span> <span class="st">"Fertilization °C"</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"CMB ν estimate (log scale, with 95% CI)"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Treatment | Fert °C"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"CMB dispersion structure on the coral data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/coral-nu-plot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>CMB ν by treatment, with 95% confidence intervals. All warm-fertilization cells (red) are clearly overdispersed. Control-fertilization cells (blue) straddle binomial, with O30S30 hinting at underdispersion.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-on-what-we-actually-care-about" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals-on-what-we-actually-care-about">Confidence intervals on what we actually care about</h3>
<p>The dispersion table is the methodological finding. The biological question is “by how much does each priming strategy raise fertilization success at warm temperature, and how confident are we in that number?” That is the marginal-mean question, and the answer depends on the dispersion model.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>em_tables <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (m <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"binomial"</span>, <span class="st">"cmb_by_treat"</span>)) {</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  f <span class="ot">&lt;-</span> fits[[m]]<span class="sc">$</span>fit</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(f)) <span class="cf">next</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  em <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(f, <span class="sc">~</span> fert_temp <span class="sc">*</span> treatment,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">at =</span> <span class="fu">list</span>(<span class="at">time =</span> <span class="fl">1.25</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  em_tables[[m]] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(em) <span class="sc">|&gt;</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">model =</span> m, <span class="at">ci_width =</span> asymp.UCL <span class="sc">-</span> asymp.LCL)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions
NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(em_tables) <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(model, fert_temp, treatment, ci_width) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> model, <span class="at">values_from =</span> ci_width,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">names_prefix =</span> <span class="st">"ci_"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">caption =</span> <span class="st">"95% CI widths on the marginal predicted rate per cell"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>95% CI widths on the marginal predicted rate per cell</caption>
<thead>
<tr class="header">
<th style="text-align: left;">fert_temp</th>
<th style="text-align: left;">treatment</th>
<th style="text-align: right;">ci_binomial</th>
<th style="text-align: right;">ci_cmb_by_treat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O27S27</td>
<td style="text-align: right;">0.0224</td>
<td style="text-align: right;">0.0168</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O27S27</td>
<td style="text-align: right;">0.0485</td>
<td style="text-align: right;">0.0690</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O27S30</td>
<td style="text-align: right;">0.0220</td>
<td style="text-align: right;">0.0162</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O27S30</td>
<td style="text-align: right;">0.0594</td>
<td style="text-align: right;">0.0887</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O30S27</td>
<td style="text-align: right;">0.0313</td>
<td style="text-align: right;">0.0352</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O30S27</td>
<td style="text-align: right;">0.0531</td>
<td style="text-align: right;">0.0689</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: left;">O30S30</td>
<td style="text-align: right;">0.0296</td>
<td style="text-align: right;">0.0163</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">O30S30</td>
<td style="text-align: right;">0.0410</td>
<td style="text-align: right;">0.0409</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The CMB CIs adjust the binomial baseline up where the data are overdispersed and down where they are not. Warm-fertilization cells widen by 30 to 50 percent relative to binomial, with one exception: O30S30 at warm has the mildest overdispersion of the four warm cells (ν ≈ 0.30, closest to binomial) and ends up at essentially the binomial width. Control cells either widen slightly (O30S27, the one clearly overdispersed control cell) or tighten below binomial. The O30S30 cell at control is the cleanest example: binomial 0.030, CMB 0.016, almost half.</p>
<p>That asymmetric correction is the practical payoff. Dispersion is not just a parameter we estimate, it shifts how confident we are in every cell-level rate, in the right direction for each cell.</p>
</section>
<section id="sharpening-the-biological-finding" class="level3">
<h3 class="anchored" data-anchor-id="sharpening-the-biological-finding">Sharpening the biological finding</h3>
<p>With dispersion correctly modeled, we can ask the question the original paper asked, but with calibrated standard errors. At warm fertilization (30°C), which priming strategy works?</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>em_30 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(fits<span class="sc">$</span>cmb_by_treat<span class="sc">$</span>fit, <span class="sc">~</span> treatment,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">at =</span> <span class="fu">list</span>(<span class="at">fert_temp =</span> <span class="fu">factor</span>(<span class="dv">30</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">30</span>)),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">time      =</span> <span class="fl">1.25</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(em_30, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE  df z.ratio p.value
 O27S27 - O27S30   0.3861 0.152 Inf   2.541  0.0538
 O27S27 - O30S27   0.3062 0.137 Inf   2.235  0.1139
 O27S27 - O30S30  -0.2651 0.127 Inf  -2.087  0.1573
 O27S30 - O30S27  -0.0799 0.142 Inf  -0.563  0.9430
 O27S30 - O30S30  -0.6513 0.132 Inf  -4.922  &lt;.0001
 O30S27 - O30S30  -0.5714 0.115 Inf  -4.974  &lt;.0001

Results are given on the log odds ratio (not the response) scale. 
P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<p>Three things sit in that table. First, double-priming (O30S30) significantly outperforms each single-priming strategy, both contrasts at p &lt; 0.0001 with effect sizes near 0.6 on the log-odds scale. Second, double-priming does not significantly beat no priming (p = 0.16). Third, single-priming does not improve on no priming either; the O27S27 vs O27S30 contrast is even marginally significant in the wrong direction (p = 0.054), meaning no priming was slightly better than priming sperm alone.</p>
<p>This sharpens the paper’s conclusion. The original analysis said priming helps and double-priming helps most. The CMB-calibrated version says something more pointed: you have to prime <em>both</em> gametes. Single-priming does not significantly outperform no priming, and may even be marginally worse. The only thing that lets us make that claim cleanly is calibrated uncertainty on each contrast, which required the right dispersion model.</p>
<p>The variability hint in the paper’s discussion now has both halves: priming both gametes restored the mean and the consistency of fertilization, and we can put numbers on each.</p>
</section>
</section>
<section id="when-to-use-what" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-what">When to use what</h2>
<p>CMB is not the answer to every proportion-regression problem.</p>
<p>If your data are clearly overdispersed and the dispersion looks roughly constant across groups, use beta-binomial. It is faster, well-supported, and what your reviewers will expect.</p>
<p>If your counts are nominally bounded but rarely come near the bound, and the dispersion goes in only one direction, CMP with an offset is a defensible workaround. This is the situation I originally had, and it works fine until you ask it to simulate.</p>
<p>If your counts can hit the bound, the dispersion is heterogeneous across groups, or you suspect any sub-binomial variance in any subgroup, CMB is the right tool. The standard alternatives fail in this regime in ways that are hard to detect unless you specifically look for them.</p>
<p>A few warning signs:</p>
<ul>
<li>Your binomial residuals show clear structure (cells systematically over or under predicted relative to binomial expectation).</li>
<li>Variance ratios (observed variance over binomial expectation) differ across subgroups, or cross 1.</li>
<li>A Pearson chi-square comes in well below the residual degrees of freedom.</li>
<li>A beta-binomial with per-group dispersion fails to converge, or pegs rho near zero in some groups but clearly above zero in others.</li>
</ul>
<p>Any one of these is a hint that the family you are using cannot describe what the data are doing.</p>
</section>
<section id="bottom-line" class="level2">
<h2 class="anchored" data-anchor-id="bottom-line">Bottom line</h2>
<p>For bounded count data, the binomial baseline is correct only when the data are well-behaved. Real data often are not. The standard upgrade path is beta-binomial, but BB can only ever inflate variance above binomial. When the data want sub-binomial variance, BB hits its <code>rho &gt;= 0</code> wall, sometimes silently, sometimes by refusing to converge.</p>
<p>CMB fixes this. It is the binomial analogue of CMP, it covers both dispersion directions through a single ν parameter, and it respects the upper bound by construction. With the implementation linked below it slots into the standard <code>glmmTMB</code> workflow.</p>
<p>The coral example showed what this buys you on a real study: a sharper biological claim than the original analysis could make, with properly calibrated intervals on each contrast. The dispersion structure the authors had only described qualitatively is now an estimable, testable feature of the fit.</p>
</section>
<section id="getting-cmb-in-your-r-session" class="level2">
<h2 class="anchored" data-anchor-id="getting-cmb-in-your-r-session">Getting CMB in your R session</h2>
<p>The CMB family is not on CRAN. For now it lives on two public forks:</p>
<ul>
<li>TMB side, the auto-differentiable likelihood: <a href="https://github.com/jbogomolovas2/adcomp/tree/cmb-family">github.com/jbogomolovas2/adcomp@cmb-family</a></li>
<li>glmmTMB side, the formula interface: <a href="https://github.com/jbogomolovas2/glmmTMB/tree/cmb-family">github.com/jbogomolovas2/glmmTMB@cmb-family</a></li>
</ul>
<p>Install both with the snippet above, write <code>family = compbinomial</code> in your <code>glmmTMB()</code> call, and the rest is the standard workflow you already know. Issues and pull requests are welcome on either fork. If <code>compbinomial</code> ends up useful for your work I would be glad to hear about it.</p>
</section>
<section id="acknowledgements" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgements">Acknowledgements</h2>
<p>This post stands on a lot of other people’s code. The CMB distribution work by <span class="citation" data-cites="kadane2016cmb">(<a href="#ref-kadane2016cmb" role="doc-biblioref">Kadane 2016</a>)</span> and the COMMultReg package by Andrew Raim <span class="citation" data-cites="COMMultReg">(<a href="#ref-COMMultReg" role="doc-biblioref">Raim, n.d.</a>)</span> provided the distribution-level reference implementation that I checked the TMB-side density against. The mean parameterization follows the pattern Huang <span class="citation" data-cites="huang2017meanCMP">(<a href="#ref-huang2017meanCMP" role="doc-biblioref">Huang 2017</a>)</span> introduced for CMP. TMB <span class="citation" data-cites="kristensen2016TMB">(<a href="#ref-kristensen2016TMB" role="doc-biblioref">Kristensen et al. 2016</a>)</span> handled the automatic differentiation that made the inner Newton solve tractable, and glmmTMB <span class="citation" data-cites="brooks2017glmmTMB">(<a href="#ref-brooks2017glmmTMB" role="doc-biblioref">Brooks et al. 2017</a>)</span> provided the family-dispatch and dispformula machinery that the CMB family slots into. The coral data is from Puisay et al. <span class="citation" data-cites="puisay2024coral">(<a href="#ref-puisay2024coral" role="doc-biblioref">Puisay et al. 2024</a>)</span>, archived openly on Zenodo <span class="citation" data-cites="puisay2024coral_data">(<a href="#ref-puisay2024coral_data" role="doc-biblioref">Puisay et al. 2023</a>)</span>, which is what made the real-data demonstration possible. R package citations were generated with <code>grateful</code> <span class="citation" data-cites="grateful">(<a href="#ref-grateful" role="doc-biblioref">Rodrı́guez-Sánchez, n.d.</a>)</span>.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-brooks2017glmmTMB" class="csl-entry" role="listitem">
Brooks, Mollie E., Kasper Kristensen, Koen J. van Benthem, Arni Magnusson, Casper W. Berg, Anders Nielsen, Hans J. Skaug, Martin Mächler, and Benjamin M. Bolker. 2017. <span>“<span class="nocase">glmmTMB</span> Balances Speed and Flexibility Among Packages for Zero-Inflated Generalized Linear Mixed Models.”</span> <em>The R Journal</em> 9 (2): 378–400. <a href="https://doi.org/10.32614/RJ-2017-066">https://doi.org/10.32614/RJ-2017-066</a>.
</div>
<div id="ref-huang2017meanCMP" class="csl-entry" role="listitem">
Huang, Alan. 2017. <span>“Mean-Parametrized <span>Conway–Maxwell–Poisson</span> Regression Models for Dispersed Counts.”</span> <em>Statistical Modelling</em> 17 (6): 359–80. <a href="https://doi.org/10.1177/1471082X17697749">https://doi.org/10.1177/1471082X17697749</a>.
</div>
<div id="ref-kadane2016cmb" class="csl-entry" role="listitem">
Kadane, Joseph B. 2016. <span>“Sums of Possibly Associated <span>B</span>ernoulli Variables: The <span class="nocase">Conway-Maxwell-binomial</span> Distribution.”</span> <em>Bayesian Analysis</em> 11 (2): 403–20. <a href="https://doi.org/10.1214/15-BA955">https://doi.org/10.1214/15-BA955</a>.
</div>
<div id="ref-kristensen2016TMB" class="csl-entry" role="listitem">
Kristensen, Kasper, Anders Nielsen, Casper W. Berg, Hans Skaug, and Bradley M. Bell. 2016. <span>“<span>TMB</span>: Automatic Differentiation and <span>Laplace</span> Approximation.”</span> <em>Journal of Statistical Software</em> 70 (5): 1–21. <a href="https://doi.org/10.18637/jss.v070.i05">https://doi.org/10.18637/jss.v070.i05</a>.
</div>
<div id="ref-puisay2024coral_data" class="csl-entry" role="listitem">
Puisay, Antoine, Laetitia Hédouin, Rosanne Pilon, Claire Goiran, and Benoit Pujol. 2023. <span>“Data for: How Thermal Priming of Coral Gametes Shapes Fertilization Success.”</span> Zenodo. <a href="https://doi.org/10.5281/zenodo.8032394">https://doi.org/10.5281/zenodo.8032394</a>.
</div>
<div id="ref-puisay2024coral" class="csl-entry" role="listitem">
———. 2024. <span>“How Thermal Priming of Coral Gametes Shapes Fertilization Success.”</span> <em>Journal of Experimental Marine Biology and Ecology</em>. <a href="https://doi.org/10.1016/j.jembe.2023.151953">https://doi.org/10.1016/j.jembe.2023.151953</a>.
</div>
<div id="ref-COMMultReg" class="csl-entry" role="listitem">
Raim, Andrew M. n.d. <em><span>COMMultReg</span>: <span>Conway–Maxwell</span> Multinomial Regression</em>. <a href="https://github.com/andrewraim/COMMultReg">https://github.com/andrewraim/COMMultReg</a>.
</div>
<div id="ref-grateful" class="csl-entry" role="listitem">
Rodrı́guez-Sánchez, Francisco. n.d. <em><span class="nocase">grateful</span>: Facilitate Citation of <span>R</span> Packages</em>. <a href="https://pakillo.github.io/grateful/">https://pakillo.github.io/grateful/</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jbogomolovas2\.github\.io\/Julius-s-Blog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>